name: Deploy to cPanel via FTP 🚀

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🚚 Deploying to Server
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files to cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        protocol: ftp
        server-dir: public_html/
        state-name: .ftp-deploy-sync-state.json
        exclude: |
          **/.git/**
          **/.git*
          **/node_modules/**
          **/vendor/**
          **/tests/**
          **/storage/logs/**
          **/storage/framework/views/**
          **/storage/framework/cache/**
          **/storage/framework/sessions/**
          **/storage/app/public/**
          **/public/storage
          optimize.bat
          PRODUKSI.md
          rekap_project.md
          .github/**
          .ftp-deploy-sync-state.json
